#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          15
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bidirectional clipboard
vmware-user-suid-wrapper &

# fix java error
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1

# wallpaper
feh --bg-fill /home/user_replace/Wallpapers/wallpaper.jpg &

# bright
brillo_actual=$(cat /sys/class/backlight/amdgpu_bl0/brightness)

if [ "$brillo_actual" = "12" ]; then
    echo '0' > /sys/class/backlight/amdgpu_bl0/brightness && brightnessctl -q s 1 && brightnessctl -q s 0
fi

# polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar &

# picom
sleep 1
picom &
