#!/bin/bash

# bspwm
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config normal_border_color   '#28344a'
bspc config active_border_color   '#28344a'
bspc config focused_border_color  '#28344a'
bspc config presel_feedback_color '#28344a'

bspc config window_gap            15
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# fix java error
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1

# wallpaper
wallpaper=$(cat /home/user_replace/.config/bin/wallpaper)
feh --bg-fill /home/user_replace/Wallpapers/$wallpaper &

# bidirectional clipboard
vmware-user-suid-wrapper &

# polkit agent
if [ "$(pidof cmd-polkit-agent | wc -w)" -lt 2 ]; then
    /usr/bin/rofi-polkit-agent -theme /home/user_replace/.config/rofi/polkit-agent/style.rasi &
fi

# dunst
pidof dunst > /dev/null || dunst &

# sxhkd
pidof sxhkd > /dev/null || sxhkd &

# brightness
brightness=$(cat /sys/class/backlight/*/brightness)
if [ "$brightness" = "12" ]; then
    echo '0' > /sys/class/backlight/*/brightness
fi

# picom
pidof picom > /dev/null || picom --config /home/user_replace/.config/picom/picom.conf --daemon &

# polybar
if pidof "polybar" > /dev/null
then
    killall -q polybar && sleep 1
fi
polybar &
