#! /bin/bash

# bspwm
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          15
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bidirectional clipboard
vmware-user-suid-wrapper &

# fix java error
wmname LG3D &
export _JAVA_AWT_WM_NONREPARENTING=1

# wallpaper
wallpaper=$(cat /home/user_replace/.config/bin/wallpaper)
feh --bg-fill /home/user_replace/Wallpapers/$wallpaper &

# dunst
if pgrep -x "xfce4-notifyd" > /dev/null
then
    killall -q xfce4-notifyd
fi
pgrep -x dunst > /dev/null || dunst &

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# brightness
brightness=$(cat /sys/class/backlight/*/brightness)

if [ "$brightness" = "12" ]; then
    echo '0' > /sys/class/backlight/*/brightness
fi

# picom
if pgrep -x "picom" > /dev/null
then
    killall -q picom && sleep 1
fi
picom --config /home/user_replace/.config/picom/picom.conf --daemon &

# polybar
if pgrep -x "polybar" > /dev/null
then
    killall -q polybar && sleep 1
fi
polybar &
