Section "InputClass"
    Identifier "Touchpad"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"
    Option "ClickMethod" "clickfinger"
    Option "DisableWhileTyping" "true"
    Option "AccelProfile" "adaptive"
    Option "Speed" "0.2"
EndSection
